In [ ]:
import pandas as pd

df = pd.read_csv("policy_sales_data.csv")

df.head()

,Customer_ID,Vehicle_ID,Vehicle_Value,Policy_Tenure,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date
0,1,V1,100000,3,300,2024-08-27,2025-08-27,2028-08-26
1,2,V2,100000,3,300,2024-04-14,2025-04-14,2028-04-13
2,3,V3,100000,2,200,2024-05-23,2025-05-23,2027-05-23
3,4,V4,100000,3,300,2024-06-19,2025-06-19,2028-06-18
4,5,V5,100000,2,200,2024-02-15,2025-02-14,2027-02-14

In [ ]:
claim_data = df.copy()

claim_data["Claim_Amount"] = 100000 * 0.10
claim_data["Claim_Date"] = claim_data["Policy_Start_Date"]
claim_data["Claim_Type"] = 1

claims = claim_data.sample(frac=0.3)

claims = claims[[
"Customer_ID",
"Vehicle_ID",
"Claim_Amount",
"Claim_Date",
"Claim_Type"
]]

claims.to_csv("claims_data.csv", index=False)

claim_data.head

,Customer_ID,Vehicle_ID,Vehicle_Value,Policy_Tenure,Premium,Policy_Purchase_Date,Policy_Start_Date,Policy_End_Date,Claim_Amount,Claim_Date,Claim_Type
0,1,V1,100000,3,300,2024-08-27,2025-08-27,2028-08-26,10000.0,2025-08-27,1
1,2,V2,100000,3,300,2024-04-14,2025-04-14,2028-04-13,10000.0,2025-04-14,1
2,3,V3,100000,2,200,2024-05-23,2025-05-23,2027-05-23,10000.0,2025-05-23,1
3,4,V4,100000,3,300,2024-06-19,2025-06-19,2028-06-18,10000.0,2025-06-19,1
4,5,V5,100000,2,200,2024-02-15,2025-02-14,2027-02-14,10000.0,2025-02-14,1